name: CI/CD Docker-compose

on:
  push:
    branches:
      - master
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install npm dependencies and run tests
        run: npm ci && npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: docker buildx build --push --tag ghcr.io/${{ github.actor }}/base:${{ github.sha }} .

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f /home/ubuntu/actions-runner/_work/base/base/docker-compose.yml pull
          docker-compose -f /home/ubuntu/actions-runner/_work/base/base/docker-compose.yml down
          docker-compose -f /home/ubuntu/actions-runner/_work/base/base/docker-compose.yml up -d --build
